### ISSUE TITLE
ModuleNotFoundError from dependancy

### ISSUE THREAD

**Issue by partrita** [nayoung10/ASSD#2]
To `Pre-processing for MEAN` I need to install those packages.

- pandas
- tqdm
- biopython

I solved this by this commands

```bash
conda activate AGN
conda install pandas tqdm biopython -y
```

**Comment by nayoung10** [comment]
If install.sh runs properly, it should install the packages you've mentioned :) 
I've updated the install.sh code so that the conda environment activates even without shell initialization, so running `source scripts/install.sh` should automatically install the packages that you've mentioned.

I appreciate your interest in our work :)
