### ISSUE TITLE
Problems I encounter doing install.sh

### ISSUE THREAD

**Issue by partrita** [nayoung10/ASSD#5]
When I was tried this shell script on my local linux.

```bash
source script/install.sh
```

It creates chaos everywhere. It is risky.
Therefore, I prefer use below code.

```bash
conda env create -f environment.yml # in root folder of AGN
conda activate AGN
python -m pip install -e vendor/esm
python -m pip install -r requirements.txt
python -m pip install -e .
g++ -static -03 -ffast-math -lm -o MEAN/evaluation/TMscore MEAN/evaluation/TMscore.cpp
```

then check CUDA available in python

```python
import torch
torch.cuda.is_available() # Must be True
```

I hope there is another safe option of installation, like docker image.
Thanks.

**Comment by nayoung10** [comment]
I respectfully disagree that the script creates chaos, because the code you suggest is exactly the same code in the bash script. We're not considering a docker installation option for now. Thanks.

**Comment by partrita** [comment]
> I respectfully disagree that the script creates chaos, because the code you suggest is exactly the same code in the bash script. We're not considering a docker installation option for now. Thanks.

If you're feeling upset, I apologize. 

The most challenging aspect I encountered when attempting it was the `pip install -r requirement.txt` section within the bash shell script.

In my case, due to the failure of conda virtual env activation in shell script. After `pip install` command executed in the local Python location, it leading to a messy. As you're likely aware, dependency issues in Python can be quite challenging.

Moreover, setting up CUDA for PyTorch can be quite intricate. Therefore, for me, `pip` is the option I'd prefer to avoid the most. Using tools like `poetry`, `pipenv`, `pixi`, or `mamba` can help alleviate these headaches.

**Comment by nayoung10** [comment]
Yes, we're aware of the conda installation failure, and that's why we have included `# TIP: Temporarily comment out the lines 15-22 in install.sh in case the conda installation fails.` in the readme file. 

We recognize the challenges in setting up the environment, but this repository is not intended to serve as a fully developed software package for users; rather, it is merely a prototype for our recently published research paper. We appreciate your understanding and interest to our work :)

**Comment by nayoung10** [comment]
I have modified the installation script so that it automatically handles conda installation failure. It still uses `pip` to install the packages required by [ByProt](https://github.com/BytedProtein/ByProt), one of the base repos for this project, but I hope this update alleviates some inconvenience :).
